### ISSUE TITLE
Error in constructors + calls

### ISSUE THREAD

**Issue by lcnvdl** [connec/squash#2]
Hi! I'm getting a problem. This is my code:

```
var MyClass = function() {
    this.list = function () {
        let p = new Promise((resolve, reject) => {
            dbManager.list().then(data => {
                let entities = data.map(entity => new Attachment().deserialize(entity));
                resolve(entities);
            }).catch(err => reject(err));
        });

        return p;
    };
}
```

Squashified version (post beutified)
```
var MyClass = function() {
        this.list = function() {
            let n = new Promise((n, t) => {
                e.list().then(e => {
                    let t = e.map(e => new Attachment.deserialize(e));
                    n(t)
                }).catch(e => t(e))
            });
            return n
        };
}
```

As you can see, the line new Attachment.deserialize(e) is wrong, because the class is Attachment, not Attachment.deserialize.

In that case, must be: new Attachment().deserialize(e)

**Comment by connec** [comment]
Thanks for the issue, but I'm going to close it since this repository is going to be archived. squash has been unmaintained for some time, so it would be best to use something else.

---

In the unlikely event that this is still relevant, this must in fact be a bug in `uglify` since squash delegates all the minification to it.
